### ISSUE TITLE
TextView setup bug

### ISSUE THREAD

**Issue by kevinzak** [bluecadet/Cinder-BluecadetViews#102]
If you use _TextView::setup_ , you need to use ALL of the optional parameters in order for the next to render. Specifically, you need to set the last parameter, which is MaxWidth. The optional parameter sets this to -1 by default, and this should just allow the text to flow as wide as its needed. Instead it just won't render.

**Comment by benjaminbojko** [comment]
@kevinzak If you change the last default value to `0` instead of `-1`, does that fix it? If so, could you make that change and create a PR?

**Comment by kevinzak** [comment]
Sure thing I'll check it out.

**Comment by kevinzak** [comment]
Can confirm if you just set to 0 instead of -1. I'll make the changes and make a PR today.

**Comment by benjaminbojko** [comment]
Fixed in #105
