### ISSUE TITLE
Setting stroke width of StrokedRoundedRectView to 0.0f colors entire shape

### ISSUE THREAD

**Issue by adielfernandez** [bluecadet/Cinder-BluecadetViews#123]
Stroke width works for very small, non-zero values like 0.001f, but ends up covering entire shape at 0.0f. Can be seen in ViewTypesSample app by setting stroke width to zero and turning off timeline animations.

**Comment by benjaminbojko** [comment]
Thanks for testing @adielfernandez! Fixed in the latest commit on https://github.com/bluecadet/Cinder-BluecadetViews/pull/121.
