### ISSUE TITLE
Incorporate multi-screen, multi-touch support from previous projects

### ISSUE THREAD

**Issue by benjaminbojko** [bluecadet/Cinder-BluecadetViews#128]
Things to do:
- [x] Combine code from `TouchWin8` and `MultiNativeTouchDriver` into a single `NativeMultiScreenTouchDriver`
- [x] Add code from `MultiNativeTouchDriver` and `TouchWin8` and
  - [ ] Move the touch script to `src/bluecadet/touch/drivers`
  - [ ] Namespace it under `bluecadet::touch::drivers`
  - [ ] Add a disclaimer/comment to both the `.h` and `.cpp` with a link to where the code came from and attribution to the author
- [ ] Add `AppBase` logic to detect the number of displays and automatically choose the correct native touch driver if native touch is enabled (and TUIO isn't)

**Comment by benjaminbojko** [comment]
@shi-weili can we close this?

**Comment by shi-weili** [comment]
@benjaminbojko yep! It's already merged.

**Comment by benjaminbojko** [comment]
Thanks! Sorry to bug you on your vacation; Was hoping you wouldn't read yet haha
